### ISSUE TITLE
Invoice should be downloaded with the invoice number, with which it is uploaded

### ISSUE THREAD

**Issue by mohitsharma-22** [ColoredCow/portal#1299]
Currently, it is downloaded with counter number .501..502 etc..

**Comment by deepankar-sajwan** [comment]
The issue is fixed please refer screenshot

File is available as per invoice no

![image](https://user-images.githubusercontent.com/96309135/169756167-270800e3-ea2a-4687-80bd-43af59e64ef6.png)


Download file has same name as invoice file name

![image](https://user-images.githubusercontent.com/96309135/169756448-d250d174-0f62-4639-a9f9-8173bb6c72a2.png)
