### ISSUE TITLE
Issue when adding channel through Create channel button

### ISSUE THREAD

**Issue by deepankar-sajwan** [ColoredCow/portal#1915]
**Describe the bug**
When channel is added through modal available on create channel following issues our occuring

- When nothing is input in channel name and save is clicked the error is shown in background and modal disappears

Input nothing in channel name

![image](https://user-images.githubusercontent.com/96309135/179763820-1d009c65-f699-417b-a87c-9798471b7585.png)

The error seems related to name field of new application form

![image](https://user-images.githubusercontent.com/96309135/179764028-658e7478-b621-43a5-9d2f-88963e341bed.png)

-  Also when channel name is added the success message is static on screen 

![image](https://user-images.githubusercontent.com/96309135/179765337-d63cd11d-2ece-44e5-8d58-55216688f826.png)

![image](https://user-images.githubusercontent.com/96309135/179765438-ab558dd1-6e6a-46c6-953f-b9a0229fe816.png)

**To Reproduce**
1. Go to HR
2. Click on Recruitment
3. Click on the Add new application button
4. Clink on Create Channel

**Expected behavior**

- Enable save changes button only when any text is input for channel name

- The success message on channel creation should disapear after 5 seconds, and should not be static

**Comment by GauravGusain98** [comment]
### Breakdown

- [ ] Submit the add channel form using ajax call in JS instead of normal PHP submit. [Reference Link](https://linuxhint.com/submit-ajax-forms/)
- [ ] Check how you can pass URL from PHP to JS
- [ ] Check how you can get errors in ajax call
- [ ] Once you get an error show the errors in the add channel modal instead of showing it on add application form
- [ ] If you don't get the error then close the modal. (Need to check how to close modal using js)
- [ ] In the backend part where you are receiving the ajax request, instead of returning a view, return success or fail message, which will be received by the ajax request.

**Comment by GauravGusain98** [comment]
Working fine. Closing
