### ISSUE TITLE
AMC tab not getting unselected

### ISSUE THREAD

**Issue by GauravGusain98** [ColoredCow/portal#2784]
**Bug Raised By**
@GauravGusain98 

**Describe the bug**
In the project listing page, when we change the tabs for `active`, `halted`, `AMC`, and `inactive` projects the AMC projects tab remains active once selected and does not get inactive. This causes a bad user experience as it can cause confusion for the user as he is not aware about the correct active tab. 

**To Reproduce**
1. Go to Projects page from CRM->projects
2. Click on AMC tab
3. Now change the tab 
4. The AMC tab still is active
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54376313/213964809-b75126c7-7cc5-4493-afc7-b0020a95e97c.png">

**Expected behavior**
The tab should only be active it is selected. 

**Environment on which the bug is occurring**
ALL

**Point of contact for guidance**
If stuck please post your doubt on portal channel in Google Chat

**Comment by GauravGusain98** [comment]
**Basics Concept - 1 pointer:**
- [ ] Read about Models in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Views in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Routes in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Controller in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read about Services files in Laravel. Share your understanding of why we use them in the task comment in your own language
- [ ] Read how we can print a value in Laravel using dd()
- [ ] Try printing `hello world` using the `dd` function

**Requests - 1 pointer**
- [ ] Read about the GET and POST methods and how they are used in an URL. 
- [ ] Read about Laravel [HTTP Request](https://laravel.com/docs/8.x/requests)
- [ ] Understand how current project page tabs are working and share your understanding in the comment
- [ ] Figure out where the value of the tab is going. Share the name of all important functions, routes, etc. that are being used for handling tabs value
- [ ] Figure out the issue that is happening and fix it.

**Comment by rajneeshweb** [comment]
**Basics Concept - 1 pointer**
- [Previously Answered](https://github.com/ColoredCow/portal/issues/2781#issuecomment-1407372506)

<br/>

**Requests - 1 pointer**

- GET and POST methods.
GET and POST are the commonly used HTTP methods when making a request to a server via an URL.
GET is used to retrieve data from a server specified in the request URL. The parameters of the request are passed as part of the URL, in the query string.
The query string consists of a set of key-value pairs separated by an "&" symbol. The keys and values are separated by an "=" symbol. For example,
https://www.example.com/search?q=dogs&sort=relevance
The "q" and "sort" parameters are being passed to the server as part of the GET request.
POST is used to send a block of data to the server for processing. the data is sent as a part of the message body It is typically used when we want to submit a form on a web page for example,
when we log in to a website The parameters of a POST request are sent in the body of the request, rather than as part of the URL.
In general, GET requests are used for retrieving data from a server, while POST requests are used for sending data to a server.

- Laravel [HTTP Request](https://laravel.com/docs/8.x/requests)
HTTP request in Laravel is represented by an instance of the Illuminate\Http\Request class. This class provides API for accessing information about the incoming request, such as its method, URL, headers, and input data.

- How current project page tabs are working.
Tabs view part is defined in views/menu_header.blade.php and then include in index.blade.php.
Tabs functions are defined in Services/ProjectService.php. function getListTabCounts. A service file is a class that provides the functionality that the class provides, and that can be reused in multiple other parts of the application.
Tabs data query model is defined in Entitie/Project.php

- Tabs functions, routes.
function scopeIsAMC
function getListTabCounts

**Comment by GauravGusain98** [comment]
### Testing feedback
Now AMC tab is working but the halted tab is broken
![Uploading image.png…]()
