### ISSUE TITLE
Can't view application details in HR module

### ISSUE THREAD

**Issue by Ashutosh6481** [ColoredCow/portal#3320]
When clicking on view to see the applicant details, it throws the error "foreach() argument must be of type array|object, null given"

![Screenshot (152)](https://github.com/ColoredCow/portal/assets/112390100/2d1a21d1-32df-4436-902b-88a143e3fb5f)

1. Hover pointer to 'HR and click on Recruitment'
![Screenshot (150)](https://github.com/ColoredCow/portal/assets/112390100/f3677597-6e75-433b-b433-c15ac51b939f)

2. Click on 'click on view'
![Screenshot (151)](https://github.com/ColoredCow/portal/assets/112390100/ff811937-63d1-4082-b0e4-57160653a0f3)

3. Then we will get the error.

4. The error is caused because of the code in line 109 and 110  
![Screenshot (153)](https://github.com/ColoredCow/portal/assets/112390100/5ff8c1cd-5852-45fe-b182-9730172d61e0)

5. If we remove "->value" after $applicationFormDetails 
![Screenshot (154)](https://github.com/ColoredCow/portal/assets/112390100/25e84532-06aa-489c-983e-4900c75f8512)

6. We no longer get the error and can view the applicant details.
![Screenshot (155)](https://github.com/ColoredCow/portal/assets/112390100/7ee5b3ca-c5a3-44cc-86a7-6dc3014b9ca1)

**Comment by Ayush8923** [comment]
@Ashutosh6481 As far as I can check, it's working fine on the UAT environment and also it's working on the production environment. I think there are some data missing in your local system that's why this error is happing here. As far as I check in your step number-5, you didn't remove directly `->value`. First, you need to check, what this code is working also we need to check why we need to check the `->value` from here. And after removing it, is it not doing any other functionality effect?
